// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9CVmAYZQ_Eavi0RYnMxZRcEnVopD97_c',
    appId: '1:701786526477:web:b6ac47c6658ab1d7a05644',
    messagingSenderId: '701786526477',
    projectId: 'bark-8bf26',
    authDomain: 'bark-8bf26.firebaseapp.com',
    storageBucket: 'bark-8bf26.appspot.com',
    measurementId: 'G-9YZSL71CNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPTVU8kP5D5ah3pQIhQLbr674vYemd47k',
    appId: '1:701786526477:android:0a2320397a8bbed8a05644',
    messagingSenderId: '701786526477',
    projectId: 'bark-8bf26',
    storageBucket: 'bark-8bf26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFisemyDK0isWpPqNCMp-8KzwlGjoq548',
    appId: '1:701786526477:ios:8d22db1b246495f4a05644',
    messagingSenderId: '701786526477',
    projectId: 'bark-8bf26',
    storageBucket: 'bark-8bf26.appspot.com',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFisemyDK0isWpPqNCMp-8KzwlGjoq548',
    appId: '1:701786526477:ios:e0a7fbcb18ce12c3a05644',
    messagingSenderId: '701786526477',
    projectId: 'bark-8bf26',
    storageBucket: 'bark-8bf26.appspot.com',
    iosBundleId: 'com.example.petapp.RunnerTests',
  );
}
